"""add doctor profile fields

Revision ID: 60ee429b4502
Revises: c4c52cd7c5f7
Create Date: 2026-07-29 17:23:51.616357
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ee429b4502'
down_revision: Union[str, None] = 'c4c52cd7c5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('specialty', sa.String(length=255), nullable=True))
    op.add_column('doctors', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('doctors', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('doctors', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'address')
    op.drop_column('doctors', 'phone')
    op.drop_column('doctors', 'date_of_birth')
    op.drop_column('doctors', 'specialty')
    # ### end Alembic commands ###
