"""add_medical_history_exam_clinical_context

Revision ID: 9f6198f5ebef
Revises: 1da876614723
Create Date: 2026-07-18 04:51:39.046377
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6198f5ebef'
down_revision: Union[str, None] = '1da876614723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('structured_findings', sa.JSON(), nullable=True),
    sa.Column('gradcam_path', sa.String(length=500), nullable=True),
    sa.Column('comparison_result', sa.JSON(), nullable=True),
    sa.Column('report_text_clinical', sa.Text(), nullable=True),
    sa.Column('report_text_patient', sa.Text(), nullable=True),
    sa.Column('validation_result_clinical', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['doctors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medical_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('smoking_status', sa.Enum('never', 'former', 'current', name='smoking_status_enum', create_constraint=True), nullable=True),
    sa.Column('prior_pneumonia', sa.Boolean(), nullable=False),
    sa.Column('tuberculosis_history', sa.Boolean(), nullable=False),
    sa.Column('copd', sa.Boolean(), nullable=False),
    sa.Column('asthma', sa.Boolean(), nullable=False),
    sa.Column('heart_disease', sa.Boolean(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), nullable=False),
    sa.Column('hypertension', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['doctors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('exam_clinical_context',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('fever', sa.Boolean(), nullable=True),
    sa.Column('cough', sa.Boolean(), nullable=True),
    sa.Column('chest_pain', sa.Boolean(), nullable=True),
    sa.Column('shortness_of_breath', sa.Boolean(), nullable=True),
    sa.Column('oxygen_saturation', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('body_temperature', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_clinical_context')
    op.drop_table('patient_medical_history')
    op.drop_table('exams')
    # ### end Alembic commands ###
